app: template-service

image:
  name: nelson9291/template
  tag: latest

namespace: default

labels:
  owner: alex

replicas:
  min: 1
  max: 1

averageUtilization:
  cpu: 50
  memory: 80

variables:
  KEYCLOAK_REALM: "template"
  KEYCLOAK_CLIENT: "template-service"
  KEYCLOAK_SECRET: 55dfb226-6360-4222-91de-ee27d804ebe2
  KEYCLOAK_URL: https://javaforall.tech/oauth/auth/
  SPRING_PROFILES_ACTIVE: prod