apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    owner: {{ .Values.labels.owner }}
spec:
  selector:
    project: {{ .Values.app }}  #selecting PODS with those Labels
  ports:
    - name: {{ .Values.app }}
      protocol: TCP
      port: 8080 #port loadBalancer
      targetPort: 8080 #port pod
  type: ClusterIP