#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: {{ .Chart.Name }}
#  annotations:
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    app.kubernetes.io/instance: {{ .Release.Name }}
#    app.kubernetes.io/managed-by: {{ .Release.Service }}
#spec:
#  ingressClassName: nginx
#  tls:
#    - hosts:
#        - {{ .Values.host }}
#      secretName: {{ .Values.ingress.nameSecretTls }}
#  rules:
#    - host: {{ .Values.host }}
#      http:
#        paths:
#          - path:  {{ .Values.ingress.prefix }}
#            pathType: Prefix
#            backend:
#              service:
#                name: {{ .Values.app }}
#                port:
#                  number: 8080

{{- if .Values.ingress.enabled -}}
{{- $fullName := include "microservice.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "microservice.labels" . | indent 4 }}
    {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
    secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ default "/api" . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{- end }}
  {{- end }}
{{- end }}