apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.ingress.nameSecretTls }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path:  {{ .Values.ingress.prefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app }}
                port:
                  number: 8080