apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    owner: {{ .Values.labels.owner }}
stringData:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | b64dec | quote }}
    {{- end }}