apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    owner: {{ .Values.labels.owner }}
data:
  {{- range $key, $value := .Values.variables }}
    {{ $key }}: {{ $value }}
  {{- end }}